"""Render a generated brief as HTML and open it in the browser."""
from __future__ import annotations

import datetime
import html
import logging
import webbrowser
from pathlib import Path

import markdown as _md

logger = logging.getLogger(__name__)

_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6; max-width: 760px; margin: 0 auto; padding: 48px 24px 96px;
    color: #1a1a1a; background: #fdfdfc;
  }}
  @media (prefers-color-scheme: dark) {{
    body {{ color: #e6e6e6; background: #16171a; }}
    a {{ color: #7db3ff; }}
    .meta, hr {{ border-color: #333; }}
    .meta {{ color: #9aa0a6; }}
    code {{ background: #2a2c31; }}
  }}
  h1 {{ font-size: 1.9rem; line-height: 1.25; margin: 0 0 4px; }}
  h2 {{ font-size: 1.25rem; margin: 2.2rem 0 0.6rem; padding-bottom: 4px; border-bottom: 1px solid #ececec; }}
  @media (prefers-color-scheme: dark) {{ h2 {{ border-color: #333; }} }}
  .meta {{ color: #6b7076; font-size: 0.9rem; margin-bottom: 8px; }}
  a {{ color: #0a66c2; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  ul {{ padding-left: 1.3rem; }}
  li {{ margin: 0.3rem 0; }}
  p {{ margin: 0.7rem 0; }}
  code {{ background: #f0f0ee; padding: 1px 5px; border-radius: 4px; font-size: 0.9em; }}
  .banner {{
    font-size: 0.85rem; color: #6b7076; background: #f6f6f4;
    border: 1px solid #ececec; border-radius: 8px; padding: 10px 14px; margin-bottom: 28px;
  }}
  @media (prefers-color-scheme: dark) {{ .banner {{ background: #1e2024; border-color: #333; color: #9aa0a6; }} }}
</style>
</head>
<body>
<div class="banner">Generated by the brief agent from {source}. This is the agent's output. Read it like the intended reader would.</div>
{body}
</body>
</html>
"""


def render_and_open(brief_md: str, md_path: str | None, topic: str, open_browser: bool = True) -> str:
    """Render the brief Markdown to an HTML file and open it in the browser.

    Writes the HTML next to the Markdown file (same stem, .html). Returns the HTML
    file path. If rendering or opening fails, logs and returns "" so a run is never
    broken by the presentation step."""
    try:
        body = _md.markdown(brief_md or "", extensions=["extra", "sane_lists"])
        title = f"Brief: {topic}" if topic else "Brief"
        source = html.escape(topic or "a topic")
        page = _PAGE.format(title=html.escape(title), source=source, body=body)

        if md_path:
            out = Path(md_path).with_suffix(".html")
        else:
            stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
            out = Path.cwd() / f"brief-{stamp}.html"
        out.write_text(page, encoding="utf-8")

        if open_browser:
            webbrowser.open(out.as_uri())
        logger.info("rendered brief -> %s", out)
        return str(out)
    except Exception:
        logger.exception("could not render/open the brief HTML (the Markdown is still in output/)")
        return ""
